server:
    port: 19999
    servlet:
        context-path: /api
        session:
            timeout: 10m
    tomcat:
        uri-encoding: UTF-8
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: adminSa
        url: jdbc:h2:/Users/xiong/Program/Repository/H2/COC/coc.h2
        username: xiong
    h2:
        console:
            enabled: true
            path: /h2-console
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            INDENT_OUTPUT: true
        time-zone: GMT+8
    jpa:
        database: h2
        hibernate:
            ddl-auto: update
        show-sql: true
